### ISSUE TITLE
Cannot read property 'setMainSidebarCollapsed' of undefined

### ISSUE THREAD

**Issue by Ghkuijer** [react-admin-lte/react-admin-lte#26]
I'm getting an error when trying to use the MainSideBar component.
The class looks as follows:

  ```
 import React, { Component } from 'react';
   import { connect } from 'react-redux';
   import { MainSidebar } from 'reactjs-admin-lte';
   import * as userThunks from '../thunks/userThunks';

  class Sidebar extends Component {

    componentDidMount() {
      console.info(this.props);
      if (!this.props.authorized && !this.props.authorizationError && !this.props.loginInProgress) {
       this.props.login();
      }
   }

  render() {
    return <MainSidebar>
      <MainSidebar.UserPanel>
        <MainSidebar.UserPanel.Info>
          Hi there {this.props.currentUser ? this.props.currentUser.login : 'Anonymous'}!
        </MainSidebar.UserPanel.Info>
      </MainSidebar.UserPanel>
      <MainSidebar.Menu>
        <MainSidebar.Menu.Item>
          Projects
        </MainSidebar.Menu.Item>
        <MainSidebar.Menu.Item>
          Test Runs
        </MainSidebar.Menu.Item>
      </MainSidebar.Menu>
    </MainSidebar>;
  }

}

const mapStateToProps = (state) => {
	return {
    currentUser: state.authorization.currentUser,
    loginInProgress: state.authorization.inProgress,
    authorized: state.authorization.authorized,
    authorizationError: state.authorization.error
	};
};
const mapDispatchToProps = (dispatch) => {
	return {
    login: () => dispatch(userThunks.login())
  };
};
export default connect(mapStateToProps, mapDispatchToProps)(Sidebar);

```
The redux in the class above would not really matter I would say.

The error I'm getting:
`Cannot read property 'setMainSidebarCollapsed' of undefined
    at new MainSidebar (MainSidebar.js?7341:34)
    at eval (ReactCompositeComponent.js?063f:292)
    at measureLifeCyclePerf (ReactCompositeComponent.js?063f:73)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (ReactCompositeComponent.js?063f:291)
    at ReactCompositeComponentWrapper._constructComponent (ReactCompositeComponent.js?063f:282)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js?063f:185)
    at Object.mountComponent (ReactReconciler.js?c56c:43)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js?063f:368)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js?063f:255)
    at Object.mountComponent (ReactReconciler.js?c56c:43)`

Thanks in advance for any help!

**Comment by furcic** [comment]
same error here

**Comment by jonmpqts** [comment]
This is because `MainSidebar` is expecting an context to be available from its parent `Layout` component:

https://github.com/react-admin-lte/react-admin-lte/blob/30a4c5bac2dcfc60d64ff2a96a706b28540694a9/packages/react-admin-lte/src/Layout/Layout.tsx#L92

Are you using the `Layout` component as well or is this during a test? To see one possible way to get around this during testing is to look at the test for `MainSidebar` itself:

https://github.com/react-admin-lte/react-admin-lte/blob/master/packages/react-admin-lte/src/MainSidebar/MainSidebar.test.tsx#L14

**Comment by Ghkuijer** [comment]
That works! Thx @jonmpqts ! 

I was not using the Layout component. It didn't see it in the documentation that it was required.
I'm now trying to combine react-admin-lte with single-spa framework. Then if you use the Layout component in the main root SPA and the sidebar in one of its children it still won't work. So I moved my Sidebar to the root SPA and now it works.
