### ISSUE TITLE
Can't resolve '@react-bootstrap/pagination'

### ISSUE THREAD

**Issue by tranngocthang89** [react-admin-lte/react-admin-lte#29]
Module not found: Can't resolve '@react-bootstrap/pagination' in '...\node_modules\reactjs-admin-lte\lib\DataTable'
I'm getting an error when run demo:
`import React, { Component } from 'react';
import logo from '../../logo.svg';
import './App.css';
import  {Box} from 'reactjs-admin-lte';
class App extends Component {
  render() {
    return (
      <div className="App">
          <Box>
              <Box.Header>
                  <Box.Title>Hello, world!</Box.Title>
              </Box.Header>
              <Box.Body>
                  Thanks for choosing reactjs-admin-lte.
              </Box.Body>
          </Box>
      </div>
    );
  }
}

export default App;`

**Comment by ramonberrutti** [comment]
@tranngocthang89 how you resolve this?

**Comment by tranngocthang89** [comment]
i install some require package for bootstrap,datatables and it run :D

**Comment by viananicolas** [comment]
What packages exactly did you install? I'm having the same issue.

**Comment by DiegoRSousa** [comment]
I'm having the same issue.
@tranngocthang89  What packages exactly did you install?

**Comment by zerbinidamata** [comment]
If anyone is still facing this issue, install the @react-bootstrap pagination and react-bootstrap with the same version as in the package.json of the project, worked for me.
